### ISSUE TITLE
Provisioned Concurrency Enabled - Slow Response

### ISSUE THREAD

**Issue by KentonParton** [awslabs/aws-lambda-web-adapter#306] opened 2023-11-09 07:37 UTC
Hello!

When using aws-lambda-web-adapter (fastapi) with ProvisionedConcurrency enabled, I am still seeing a slow response time from my application, ~ 5-6 seconds. 

From what I can see in the Lambda metrics (image below), my requests are being served by a provisioned container but looking at the CloudWatch logs I can see that the FastAPI app is starting up and shutting down after a few seconds.

<img width="426" alt="Screenshot 2023-11-09 at 09 27 40" src="https://github.com/awslabs/aws-lambda-web-adapter/assets/20202312/3a679d7d-b5be-4ceb-a23f-06c91d83a192">
<img width="1387" alt="Screenshot 2023-11-09 at 09 30 26" src="https://github.com/awslabs/aws-lambda-web-adapter/assets/20202312/72bcbf0e-7f9e-4b63-8b95-e44640ca52d6">

Is there a way to keep FastAPI running in the background when provisioned concurrency is enabled so that requests are always hot?

Thanks!

**Comment by bnusunny** [comment] 2023-11-09 11:52
This is kinda strange. Let me test it and get back to you with the results.

**Comment by bnusunny** [comment] 2023-11-09 16:21
I couldn't reproduce the issue. Was the logs from the same log stream? Could you show the relevant logs with the log streams?

**Comment by bnusunny** [comment] 2023-11-18 14:08
@KentonParton Could you provide more details for this issue?

**Comment by bnusunny** [comment] 2024-01-10 06:59
@KentonParton I'm closing this issue. Please reopen if you still have this problem.

**Closed by bnusunny** 2024-01-10 06:59 UTC
